-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Enable Vector extension for embeddings
create extension if not exists vector;

-- Profiles Table (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  short_description text,
  price decimal(10, 2) not null,
  compare_price decimal(10, 2),
  category_id bigint references categories(id),
  inventory_quantity integer default 0,
  images text[], -- Array of image URLs
  featured_image text,
  is_featured boolean default false,
  is_active boolean default true,
  rating_average decimal(3, 2) default 0.00,
  rating_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Vector embedding for AI search (1536 dimensions for Gemini/OpenAI standard)
  embedding vector(768) -- Gemini Text Embedding is often 768 dimensions. Adjust if using OpenAI (1536).
);

-- Product Variants
create table product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  name text not null, -- e.g., "Size: 7", "Color: Gold"
  price_adjustment decimal(10, 2) default 0.00,
  inventory_quantity integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  order_number text unique not null,
  status text default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  total_amount decimal(10, 2) not null,
  shipping_address jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Order Items
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_id bigint references products(id),
  quantity integer not null,
  price_at_purchase decimal(10, 2) not null
);

-- Reviews Table
create table reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  user_id uuid references auth.users(id),
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Wishlist Table
create table wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- RLS Policies (Basic examples)
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

alter table products enable row level security;
create policy "Products are viewable by everyone." on products for select using ( true );

alter table orders enable row level security;
create policy "Users can view own orders." on orders for select using ( auth.uid() = user_id );

