-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Enable Vector extension for embeddings
create extension if not exists vector;

-- Profiles Table (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  short_description text,
  price decimal(10, 2) not null,
  compare_price decimal(10, 2),
  category_id bigint references categories(id),
  inventory_quantity integer default 0,
  images text[], -- Array of image URLs
  featured_image text,
  is_featured boolean default false,
  is_active boolean default true,
  rating_average decimal(3, 2) default 0.00,
  rating_count integer default 0,
  view_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Vector embedding for AI search (768 dimensions via text-embedding-004)
  embedding vector(768)
);

-- Product Images (Additional metadata)
create table product_images (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  url text not null,
  alt_text text,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Product Variants
create table product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  name text not null, -- e.g., "Size: 7", "Color: Gold"
  price_adjustment decimal(10, 2) default 0.00,
  inventory_quantity integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Coupons Table
create table coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_type text check (discount_type in ('percentage', 'fixed_amount')),
  discount_value decimal(10, 2) not null,
  min_purchase_amount decimal(10, 2) default 0.00,
  starts_at timestamp with time zone default timezone('utc'::text, now()),
  expires_at timestamp with time zone,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Coupon Usage
create table coupon_usage (
  id bigint generated by default as identity primary key,
  coupon_id bigint references coupons(id) on delete cascade not null,
  user_id uuid references auth.users(id),
  order_id bigint, -- to be linked after order creation
  used_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  order_number text unique not null,
  status text default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),
  subtotal decimal(10, 2) not null,
  tax_amount decimal(10, 2) default 0,
  shipping_amount decimal(10, 2) default 0,
  discount_amount decimal(10, 2) default 0,
  total_amount decimal(10, 2) not null,
  shipping_address jsonb,
  billing_address jsonb,
  payment_status text default 'pending',
  payment_method text default 'mock',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Order Items
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_id bigint references products(id),
  variant_id bigint references product_variants(id),
  quantity integer not null,
  price_at_purchase decimal(10, 2) not null
);

-- Reviews Table
create table reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade not null,
  user_id uuid references auth.users(id),
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  is_approved boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Wishlist Table
create table wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- Analytics Table
create table analytics (
  id bigint generated by default as identity primary key,
  event_type text not null, -- 'page_view', 'product_view', 'add_to_cart', 'purchase'
  user_id uuid references auth.users(id),
  session_id text,
  product_id bigint references products(id),
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Admin Users
create table admin_users (
  id uuid references auth.users on delete cascade not null primary key,
  role text default 'staff' check (role in ('super_admin', 'admin', 'staff')),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

alter table categories enable row level security;
create policy "Categories are viewable by everyone." on categories for select using ( true );

alter table products enable row level security;
create policy "Products are viewable by everyone." on products for select using ( true );

alter table product_images enable row level security;
create policy "Product images are viewable by everyone." on product_images for select using ( true );

alter table product_variants enable row level security;
create policy "Product variants are viewable by everyone." on product_variants for select using ( true );

alter table orders enable row level security;
create policy "Users can view own orders." on orders for select using ( auth.uid() = user_id );
create policy "Users can insert own orders." on orders for insert with check ( auth.uid() = user_id );

alter table order_items enable row level security;
create policy "Users can view own order items." on order_items for select using ( 
  exists (select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid())
);

alter table reviews enable row level security;
create policy "Reviews are viewable by everyone." on reviews for select using ( true );
create policy "Authenticated users can insert reviews." on reviews for insert with check ( auth.role() = 'authenticated' );

alter table wishlist enable row level security;
create policy "Users can view own wishlist." on wishlist for select using ( auth.uid() = user_id );
create policy "Users can modify own wishlist." on wishlist for all using ( auth.uid() = user_id );

alter table analytics enable row level security;
create policy "Only admins can view analytics." on analytics for select using ( 
  exists (select 1 from admin_users where admin_users.id = auth.uid())
);
create policy "Anyone can insert analytics." on analytics for insert with check ( true );

-- Shopping Cart Table
create table shopping_cart (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade, -- NULL for guest carts
  session_id text, -- For guest carts
  product_id bigint references products(id) on delete cascade not null,
  variant_id bigint references product_variants(id) on delete cascade,
  quantity integer not null default 1,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Shopping Cart
alter table shopping_cart enable row level security;
create policy "Users can view own cart" on shopping_cart for select using ( 
  auth.uid() = user_id or session_id = auth.jwt() ->> 'session_id' 
);
create policy "Anyone can modify own cart" on shopping_cart for all using ( 
  auth.uid() = user_id or session_id = auth.jwt() ->> 'session_id' 
);

-- Functions and Triggers
create or replace function update_product_view_count()
returns trigger as $$
begin
  if (new.event_type = 'product_view' and new.product_id is not null) then
    update products set view_count = view_count + 1 where id = new.product_id;
  end if;
  return new;
end;
$$ language plpgsql;

create trigger on_analytics_insert
  after insert on analytics
  for each row execute procedure update_product_view_count();

-- Vector similarity search function
create or replace function match_products (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  match_category_id bigint default null
)
returns table (
  id bigint,
  name text,
  slug text,
  description text,
  short_description text,
  price decimal(10, 2),
  compare_price decimal(10, 2),
  images text[],
  featured_image text,
  rating_average decimal(3, 2),
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    products.id,
    products.name,
    products.slug,
    products.description,
    products.short_description,
    products.price,
    products.compare_price,
    products.images,
    products.featured_image,
    products.rating_average,
    1 - (products.embedding <=> query_embedding) as similarity
  from products
  where (1 - (products.embedding <=> query_embedding) > match_threshold)
    and (match_category_id is null or products.category_id = match_category_id)
  order by similarity desc
  limit match_count;
end;
$$;

